<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../../../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../../../jacoco-resources/report.gif" type="image/gif"/><title>MainTest.java</title><link rel="stylesheet" href="../../../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../../../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../../../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../../../index.html" class="el_report">edu.towson.cis.cosc442.project4.coffeemaker (Mar 20, 2018 4:22:07 PM)</a> &gt; <a href="../../index.html" class="el_group">CoffeeMaker</a> &gt; <a href="../index.html" class="el_bundle">src</a> &gt; <a href="index.source.html" class="el_package">edu.towson.cis.cosc442.project4.coffeemaker</a> &gt; <span class="el_source">MainTest.java</span></div><h1>MainTest.java</h1><pre class="source lang-java linenums">package edu.towson.cis.cosc442.project4.coffeemaker;

import org.junit.*;
import static org.junit.Assert.*;

/**
 * The class &lt;code&gt;MainTest&lt;/code&gt; contains tests for the class &lt;code&gt;{@link Main}&lt;/code&gt;.
 *
 * @generatedBy CodePro at 3/19/18 5:21 PM
 * @author am
 * @version $Revision: 1.0 $
 */
<span class="fc" id="L13">public class MainTest {</span>
	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_1()
		throws Exception {

<span class="nc" id="L25">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L31">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_2()
		throws Exception {

<span class="nc" id="L44">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L50">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_3()
		throws Exception {

<span class="nc" id="L63">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L69">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_4()
		throws Exception {

<span class="nc" id="L82">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L88">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_5()
		throws Exception {

<span class="nc" id="L101">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L107">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_6()
		throws Exception {

<span class="nc" id="L120">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L126">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_7()
		throws Exception {

<span class="nc" id="L139">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L145">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_8()
		throws Exception {

<span class="nc" id="L158">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L164">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_9()
		throws Exception {

<span class="nc" id="L177">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L183">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_10()
		throws Exception {

<span class="nc" id="L196">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L202">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_11()
		throws Exception {

<span class="nc" id="L215">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L221">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_12()
		throws Exception {

<span class="nc" id="L234">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L240">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_13()
		throws Exception {

<span class="nc" id="L253">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L259">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_14()
		throws Exception {

<span class="nc" id="L272">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L278">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_15()
		throws Exception {

<span class="nc" id="L291">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L297">	}</span>

	/**
	 * Run the void addInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddInventory_16()
		throws Exception {

<span class="nc" id="L310">		Main.addInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addInventory(Main.java:206)
<span class="nc" id="L316">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_1()
		throws Exception {

<span class="nc" id="L329">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L335">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_2()
		throws Exception {

<span class="nc" id="L348">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L354">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_3()
		throws Exception {

<span class="nc" id="L367">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L373">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_4()
		throws Exception {

<span class="nc" id="L386">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L392">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_5()
		throws Exception {

<span class="nc" id="L405">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L411">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_6()
		throws Exception {

<span class="nc" id="L424">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L430">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_7()
		throws Exception {

<span class="nc" id="L443">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L449">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_8()
		throws Exception {

<span class="nc" id="L462">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L468">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_9()
		throws Exception {

<span class="nc" id="L481">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L487">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_10()
		throws Exception {

<span class="nc" id="L500">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L506">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_11()
		throws Exception {

<span class="nc" id="L519">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L525">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_12()
		throws Exception {

<span class="nc" id="L538">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L544">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_13()
		throws Exception {

<span class="nc" id="L557">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L563">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_14()
		throws Exception {

<span class="nc" id="L576">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L582">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_15()
		throws Exception {

<span class="nc" id="L595">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L601">	}</span>

	/**
	 * Run the void addRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testAddRecipe_16()
		throws Exception {

<span class="nc" id="L614">		Main.addRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.addRecipe(Main.java:83)
<span class="nc" id="L620">	}</span>

	/**
	 * Run the void checkInventory() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testCheckInventory_1()
		throws Exception {

<span class="nc" id="L633">		Main.checkInventory();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.checkInventory(Main.java:211)
<span class="nc" id="L639">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_1()
		throws Exception {

<span class="nc" id="L652">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L658">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_2()
		throws Exception {

<span class="nc" id="L671">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L677">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_3()
		throws Exception {

<span class="nc" id="L690">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L696">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_4()
		throws Exception {

<span class="nc" id="L709">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L715">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_5()
		throws Exception {

<span class="nc" id="L728">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L734">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_6()
		throws Exception {

<span class="nc" id="L747">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L753">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_7()
		throws Exception {

<span class="nc" id="L766">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L772">	}</span>

	/**
	 * Run the void deleteRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testDeleteRecipe_8()
		throws Exception {

<span class="nc" id="L785">		Main.deleteRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.deleteRecipe(Main.java:92)
<span class="nc" id="L791">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_1()
		throws Exception {

<span class="nc" id="L804">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L810">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_2()
		throws Exception {

<span class="nc" id="L823">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L829">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_3()
		throws Exception {

<span class="nc" id="L842">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L848">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_4()
		throws Exception {

<span class="nc" id="L861">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L867">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_5()
		throws Exception {

<span class="nc" id="L880">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L886">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_6()
		throws Exception {

<span class="nc" id="L899">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L905">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_7()
		throws Exception {

<span class="nc" id="L918">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L924">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_8()
		throws Exception {

<span class="nc" id="L937">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L943">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_9()
		throws Exception {

<span class="nc" id="L956">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L962">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_10()
		throws Exception {

<span class="nc" id="L975">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L981">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_11()
		throws Exception {

<span class="nc" id="L994">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L1000">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_12()
		throws Exception {

<span class="nc" id="L1013">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L1019">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_13()
		throws Exception {

<span class="nc" id="L1032">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L1038">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_14()
		throws Exception {

<span class="nc" id="L1051">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L1057">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_15()
		throws Exception {

<span class="nc" id="L1070">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L1076">	}</span>

	/**
	 * Run the void editRecipe() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testEditRecipe_16()
		throws Exception {

<span class="nc" id="L1089">		Main.editRecipe();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.editRecipe(Main.java:111)
<span class="nc" id="L1095">	}</span>

	/**
	 * Run the String inputOutput(String) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testInputOutput_1()
		throws Exception {
<span class="fc" id="L1107">		String message = &quot;&quot;;</span>

<span class="fc" id="L1109">		String result = Main.inputOutput(message);</span>

		// add additional test code here
<span class="fc" id="L1112">		assertEquals(null, result);</span>
<span class="fc" id="L1113">	}</span>

	/**
	 * Run the void main(String[]) method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMain_1()
		throws Exception {
<span class="nc" id="L1125">		String[] args = new String[] {};</span>

<span class="nc" id="L1127">		Main.main(args);</span>

		// add additional test code here
<span class="nc" id="L1130">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_1()
		throws Exception {

<span class="nc" id="L1143">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1146">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_2()
		throws Exception {

<span class="nc" id="L1159">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1162">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_3()
		throws Exception {

<span class="nc" id="L1175">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1178">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_4()
		throws Exception {

<span class="nc" id="L1191">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1194">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_5()
		throws Exception {

<span class="nc" id="L1207">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1210">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_6()
		throws Exception {

<span class="nc" id="L1223">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1226">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_7()
		throws Exception {

<span class="nc" id="L1239">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1242">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_8()
		throws Exception {

<span class="nc" id="L1255">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1258">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_9()
		throws Exception {

<span class="nc" id="L1271">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1274">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_10()
		throws Exception {

<span class="nc" id="L1287">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1290">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_11()
		throws Exception {

<span class="nc" id="L1303">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1306">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_12()
		throws Exception {

<span class="nc" id="L1319">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1322">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_13()
		throws Exception {

<span class="nc" id="L1335">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1338">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_14()
		throws Exception {

<span class="nc" id="L1351">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1354">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_15()
		throws Exception {

<span class="nc" id="L1367">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1370">	}</span>

	/**
	 * Run the void mainMenu() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMainMenu_16()
		throws Exception {

<span class="nc" id="L1383">		Main.mainMenu();</span>

		// add additional test code here
<span class="nc" id="L1386">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_1()
		throws Exception {

<span class="nc" id="L1399">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1405">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_2()
		throws Exception {

<span class="nc" id="L1418">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1424">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_3()
		throws Exception {

<span class="nc" id="L1437">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1443">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_4()
		throws Exception {

<span class="nc" id="L1456">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1462">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_5()
		throws Exception {

<span class="nc" id="L1475">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1481">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_6()
		throws Exception {

<span class="nc" id="L1494">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1500">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_7()
		throws Exception {

<span class="nc" id="L1513">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1519">	}</span>

	/**
	 * Run the void makeCoffee() method test.
	 *
	 * @throws Exception
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Test
	public void testMakeCoffee_8()
		throws Exception {

<span class="nc" id="L1532">		Main.makeCoffee();</span>

		// add additional test code here
		// An unexpected exception was thrown in user code while executing this test:
		//    java.lang.NullPointerException
		//       at edu.towson.cis.cosc442.project4.coffeemaker.Main.makeCoffee(Main.java:217)
<span class="nc" id="L1538">	}</span>

	/**
	 * Perform pre-test initialization.
	 *
	 * @throws Exception
	 *         if the initialization fails for some reason
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@Before
	public void setUp()
		throws Exception {
		// add additional set up code here
<span class="fc" id="L1552">	}</span>

	/**
	 * Perform post-test clean-up.
	 *
	 * @throws Exception
	 *         if the clean-up fails for some reason
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	@After
	public void tearDown()
		throws Exception {
		// Add additional tear down code here
<span class="fc" id="L1566">	}</span>

	/**
	 * Launch the test.
	 *
	 * @param args the command line arguments
	 *
	 * @generatedBy CodePro at 3/19/18 5:21 PM
	 */
	public static void main(String[] args) {
<span class="nc" id="L1576">		new org.junit.runner.JUnitCore().run(MainTest.class);</span>
<span class="nc" id="L1577">	}</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.7.9.201702052155</span>edu.towson.cis.cosc442.project4.coffeemaker (Mar 20, 2018 4:22:07 PM)</div></body></html>